# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
# db/seeds.rb

[
  { name: 'Grass' },
  { name: 'Fairy' },
  { name: 'Darkness' },
  { name: 'Metal' },
  { name: 'Fighting' },
  { name: 'Psychic' },
  { name: 'Fire' },
  { name: 'Water' },
  { name: 'Lightning' },
  { name: 'Dragon' },
  { name: 'Energy' },
  { name: 'Trainer' },
  { name: 'Normal' }
].each do |serie_attrs|
  CardType.find_or_create_by(name: serie_attrs[:name])
end

[
  { name: 'Rare Holo' },
  { name: 'Rare' },
  { name: 'Uncommon' },
  { name: 'Common' }
].each do |serie_attrs|
  CardRarity.find_or_create_by(name: serie_attrs[:name])
end

[
  { name: 'Base Set', release_date: '1999-09-01', image_url: 'https://den-media.pokellector.com/logos/Base-Set.logo.119.png' },
  { name: 'Gym Heroes', release_date: '2000-08-14', image_url: 'https://den-media.pokellector.com/logos/Gym-Heroes.logo.117.png' },
  { name: 'Neo Genesis', release_date: '2000-12-16', image_url: 'https://den-media.pokellector.com/logos/Neo-Genesis.logo.113.png' },
  { name: 'Legendary Collection', release_date: '2002-05-24', image_url: 'https://den-media.pokellector.com/logos/Legendary-Collection.logo.112.png' },
  { name: 'e-Card', release_date: '2002-09-15', image_url: 'https://den-media.pokellector.com/logos/e-Card.logo.108.png' },
  { name: 'EX Ruby & Sapphire', release_date: '2003-07-01', image_url: 'https://den-media.pokellector.com/logos/Ruby-Sapphire.logo.49.png' },
  { name: 'Diamond & Pearl', release_date: '2007-05-01', image_url: 'https://den-media.pokellector.com/logos/Diamond-Pearl.logo.42.png' },
  { name: 'Nintendo Promos', release_date: '2003-01-14', image_url: 'https://den-media.pokellector.com/logos/Nintendo-Promos.logo.50.png' },
  { name: 'Platinum', release_date: '2009-02-11', image_url: 'https://den-media.pokellector.com/logos/Platinum.logo.38.png' },
  { name: 'HearthGold SoulSilver', release_date: '2010-02-10', image_url: 'https://den-media.pokellector.com/logos/HeartGold-SoulSilver.logo.34.png' },
  { name: 'Call of Legends', release_date: '2011-02-09', image_url: 'https://den-media.pokellector.com/logos/Call-of-Legends.logo.33.png' },
  { name: 'Black & White Promos', release_date: '2011-04-26', image_url: 'https://den-media.pokellector.com/logos/Black-White-Promos.logo.9.png' },
  { name: 'Black & White', release_date: '2011-04-25', image_url: 'https://den-media.pokellector.com/logos/Black-White.logo.1.png' },
  { name: 'XY', release_date: '2014-02-05', image_url: 'https://den-media.pokellector.com/logos/XY.logo.142.png' },
  { name: 'Sun & Moon', release_date: '2017-02-03', image_url: 'https://den-media.pokellector.com/logos/Sun-Moon.logo.205.png' },
  { name: 'Sword & Shield', release_date: '2020-02-01', image_url: 'https://den-media.pokellector.com/logos/Sword-Shield.logo.286.png' },
  { name: 'Scarlet & Violet', release_date: '2023-03-31', image_url: 'https://den-media.pokellector.com/logos/Scarlet-Violet.logo.363.png' }
].each do |serie_attrs|
  Serie.find_or_create_by(name: serie_attrs[:name]) do |serie|
    serie.release_date = serie_attrs[:release_date]
    serie.image_url = serie_attrs[:image_url]
  end
end

[
  { name: 'Base', serie_id: '226ca42e-8e62-4bba-ade4-307667f33203', release_date: Date.parse('1999-01-09'), image_url: 'https://den-media.pokellector.com/logos/Base-Set.logo.119.png' },
  { name: 'Jungle', serie_id: '226ca42e-8e62-4bba-ade4-307667f33203', release_date: Date.parse('1999-06-16'), image_url: 'https://den-media.pokellector.com/logos/Jungle.logo.120.png' },
  { name: 'Wizards of the Coast Promos', serie_id: '226ca42e-8e62-4bba-ade4-307667f33203', release_date: Date.parse('1999-07-01'), image_url: 'https://den-media.pokellector.com/logos/Wizards-of-the-Coast-Promos.logo.125.png' },
  { name: 'Fossil', serie_id: '226ca42e-8e62-4bba-ade4-307667f33203', release_date: Date.parse('1999-10-10'), image_url: 'https://den-media.pokellector.com/logos/Fossil.logo.121.png' },
  { name: 'Base Set 2', serie_id: '226ca42e-8e62-4bba-ade4-307667f33203', release_date: Date.parse('2000-02-24'), image_url: 'https://den-media.pokellector.com/logos/Base-Set-2.logo.122.png' },
  { name: 'Team Rocket', serie_id: '226ca42e-8e62-4bba-ade4-307667f33203', release_date: Date.parse('2000-04-24'), image_url: 'https://den-media.pokellector.com/logos/Team-Rocket.logo.123.png' },
  { name: 'Gym Heroes', serie_id: '26a89bc3-fa1c-499f-b732-c85fb9f5e98f', release_date: Date.parse('2000-08-14'), image_url: 'https://den-media.pokellector.com/logos/Gym-Heroes.logo.117.png' },
  { name: 'Gym Challenge', serie_id: '26a89bc3-fa1c-499f-b732-c85fb9f5e98f', release_date: Date.parse('2000-10-16'), image_url: 'https://den-media.pokellector.com/logos/Gym-Challenge.logo.118.png' },
  { name: 'Neo Genesis', serie_id: '691f5224-ea20-472f-ad63-725366feee7b', release_date: Date.parse('2000-12-16'), image_url: 'https://den-media.pokellector.com/logos/Neo-Genesis.logo.113.png' },
  { name: 'Neo Discovery', serie_id: '691f5224-ea20-472f-ad63-725366feee7b', release_date: Date.parse('2001-06-01'), image_url: 'https://den-media.pokellector.com/logos/Neo-Discovery.logo.114.png' },
  { name: 'Southern Islands', serie_id: '691f5224-ea20-472f-ad63-725366feee7b', release_date: Date.parse('2001-07-31'), image_url: 'https://den-media.pokellector.com/logos/Southern-Islands.logo.124.png' },
  { name: 'Neo Revelation', serie_id: '691f5224-ea20-472f-ad63-725366feee7b', release_date: Date.parse('2001-09-21'), image_url: 'https://den-media.pokellector.com/logos/Neo-Revelation.logo.115.png' },
  { name: 'Neo Destiny', serie_id: '691f5224-ea20-472f-ad63-725366feee7b', release_date: Date.parse('2002-02-28'), image_url: 'https://den-media.pokellector.com/logos/Neo-Destiny.logo.116.png' },
  { name: 'Legendary Collection', serie_id: '2af01594-4b5b-4490-854f-4d40a08321f0', release_date: Date.parse('2002-05-24'), image_url: 'https://den-media.pokellector.com/logos/Legendary-Collection.logo.112.png' },
  { name: 'Expedition', serie_id: 'da0c6be0-ef85-44f1-81c2-54558fa9b5c4', release_date: Date.parse('2002-09-15'), image_url: 'https://den-media.pokellector.com/logos/Expedition.logo.109.png' },
  { name: 'Best of Game', serie_id: 'da0c6be0-ef85-44f1-81c2-54558fa9b5c4', release_date: Date.parse('2002-12-01'), image_url: 'https://den-media.pokellector.com/logos/Best-of-Game.logo.196.png' },
  { name: 'Aquapolis', serie_id: 'da0c6be0-ef85-44f1-81c2-54558fa9b5c4', release_date: Date.parse('2003-01-15'), image_url: 'https://den-media.pokellector.com/logos/Aquapolis.logo.110.png' },
  { name: 'Skyridge', serie_id: 'da0c6be0-ef85-44f1-81c2-54558fa9b5c4', release_date: Date.parse('2003-05-12'), image_url: 'https://den-media.pokellector.com/logos/Skyridge.logo.111.png' },
].each do |set_attrs|
  SerieSet.find_or_create_by(name: set_attrs[:name]) do |serie_set|
    serie_set.serie_id = Serie.find_by(name: set_attrs[:serie_name]).id
    serie_set.release_date = set_attrs[:release_date]
    serie_set.image_url = set_attrs[:image_url]
  end
end

card_types = CardType.all.map { |ct| [ct.name, ct.id] }.to_h
card_rarities = CardRarity.all.map { |cr| [cr.name, cr.id] }.to_h
serie_sets = SerieSet.all.map { |set| [set.name, set.id] }.to_h

[
  { name: "Alakazam", type: "Psychic", rarity: "Rare Holo", number: 1, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/001.png" },
{ name: "Blastoise", type: "Water", rarity: "Rare Holo", number: 2, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/002.png" },
{ name: "Chansey", type: "Normal", rarity: "Rare Holo", number: 3, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/003.png" },
{ name: "Charizard", type: "Fire", rarity: "Rare Holo", number: 4, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/004.png" },
{ name: "Clefairy", type: "Normal", rarity: "Rare Holo", number: 5, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/005.png" },
{ name: "Gyarados", type: "Water", rarity: "Rare Holo", number: 6, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/006.png" },
{ name: "Hitmonchan", type: "Fighting", rarity: "Rare Holo", number: 7, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/007.png" },
{ name: "Machamp", type: "Fighting", rarity: "Rare Holo", number: 8, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/008.png" },
{ name: "Magneton", type: "Lightning", rarity: "Rare Holo", number: 9, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/009.png" },
{ name: "Mewtwo", type: "Psychic", rarity: "Rare Holo", number: 10, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/010.png" },
{ name: "Nidoking", type: "Grass", rarity: "Rare Holo", number: 11, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/011.png" },
{ name: "Ninetales", type: "Fire", rarity: "Rare Holo", number: 12, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/012.png" },
{ name: "Poliwrath", type: "Water", rarity: "Rare Holo", number: 13, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/013.png" },
{ name: "Raichu", type: "Lightning", rarity: "Rare Holo", number: 14, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/014.png" },
{ name: "Venusaur", type: "Grass", rarity: "Rare Holo", number: 15, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/015.png" },
{ name: "Zapdos", type: "Lightning", rarity: "Rare Holo", number: 16, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/016.png" },
{ name: "Beedrill", type: "Grass", rarity: "Rare", number: 17, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/017.png" },
{ name: "Dragonair", type: "Normal", rarity: "Rare", number: 18, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/018.png" },
{ name: "Dugtrio", type: "Fighting", rarity: "Rare", number: 19, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/019.png" },
{ name: "Electabuzz", type: "Lightning", rarity: "Rare", number: 20, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/020.png" },
{ name: "Electrode", type: "Lightning", rarity: "Rare", number: 21, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/021.png" },
{ name: "Pidgeotto", type: "Normal", rarity: "Rare", number: 22, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/022.png" },
{ name: "Arcanine", type: "Fire", rarity: "Uncommon", number: 23, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/023.png" },
{ name: "Charmeleon", type: "Fire", rarity: "Uncommon", number: 24, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/024.png" },
{ name: "Dewgong", type: "Water", rarity: "Uncommon", number: 25, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/025.png" },
{ name: "Dratini", type: "Normal", rarity: "Uncommon", number: 26, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/026.png" },
{ name: "Farfetch'd", type: "Normal", rarity: "Uncommon", number: 27, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/027.png" },
{ name: "Growlithe", type: "Fire", rarity: "Uncommon", number: 28, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/028.png" },
{ name: "Haunter", type: "Psychic", rarity: "Uncommon", number: 29, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/029.png" },
{ name: "Ivysaur", type: "Grass", rarity: "Uncommon", number: 30, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/030.png" },
{ name: "Jynx", type: "Psychic", rarity: "Uncommon", number: 31, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/031.png" },
{ name: "Kadabra", type: "Psychic", rarity: "Uncommon", number: 32, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/032.png" },
{ name: "Kakuna", type: "Grass", rarity: "Uncommon", number: 33, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/033.png" },
{ name: "Machoke", type: "Fighting", rarity: "Uncommon", number: 34, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/034.png" },
{ name: "Magikarp", type: "Water", rarity: "Uncommon", number: 35, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/035.png" },
{ name: "Magmar", type: "Fire", rarity: "Uncommon", number: 36, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/036.png" },
{ name: "Nidorino", type: "Grass", rarity: "Uncommon", number: 37, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/037.png" },
{ name: "Poliwhirl", type: "Water", rarity: "Uncommon", number: 38, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/038.png" },
{ name: "Porygon", type: "Normal", rarity: "Uncommon", number: 39, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/039.png" },
{ name: "Raticate", type: "Normal", rarity: "Uncommon", number: 40, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/040.png" },
{ name: "Seel", type: "Water", rarity: "Uncommon", number: 41, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/041.png" },
{ name: "Wartortle", type: "Water", rarity: "Uncommon", number: 42, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/042.png" },
{ name: "Abra", type: "Psychic", rarity: "Common", number: 43, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/043.png" },
{ name: "Bulbasaur", type: "Grass", rarity: "Common", number: 44, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/044.png" },
{ name: "Caterpie", type: "Grass", rarity: "Common", number: 45, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/045.png" },
{ name: "Charmander", type: "Fire", rarity: "Common", number: 46, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/046.png" },
{ name: "Diglett", type: "Fighting", rarity: "Common", number: 47, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/047.png" },
{ name: "Doduo", type: "Normal", rarity: "Common", number: 48, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/048.png" },
{ name: "Drowzee", type: "Psychic", rarity: "Common", number: 49, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/049.png" },
{ name: "Gastly", type: "Psychic", rarity: "Common", number: 50, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/050.png" },
{ name: "Koffing", type: "Grass", rarity: "Common", number: 51, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/051.png" },
{ name: "Machop", type: "Fighting", rarity: "Common", number: 52, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/052.png" },
{ name: "Magnemite", type: "Lightning", rarity: "Common", number: 53, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/053.png" },
{ name: "Metapod", type: "Grass", rarity: "Common", number: 54, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/054.png" },
{ name: "Nidoran♂", type: "Grass", rarity: "Common", number: 55, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/055.png" },
{ name: "Onix", type: "Fighting", rarity: "Common", number: 56, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/056.png" },
{ name: "Pidgey", type: "Normal", rarity: "Common", number: 57, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/057.png" },
{ name: "Pikachu", type: "Lightning", rarity: "Common", number: 58, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/058.png" },
{ name: "Poliwag", type: "Water", rarity: "Common", number: 59, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/059.png" },
{ name: "Ponyta", type: "Fire", rarity: "Common", number: 60, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/060.png" },
{ name: "Rattata", type: "Normal", rarity: "Common", number: 61, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/061.png" },
{ name: "Sandshrew", type: "Fighting", rarity: "Common", number: 62, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/062.png" },
{ name: "Squirtle", type: "Water", rarity: "Common", number: 63, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/063.png" },
{ name: "Starmie", type: "Water", rarity: "Common", number: 64, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/064.png" },
{ name: "Staryu", type: "Water", rarity: "Common", number: 65, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/065.png" },
{ name: "Tangela", type: "Grass", rarity: "Common", number: 66, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/066.png" },
{ name: "Voltorb", type: "Lightning", rarity: "Common", number: 67, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/067.png" },
{ name: "Vulpix", type: "Fire", rarity: "Common", number: 68, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/068.png" },
{ name: "Weedle", type: "Grass", rarity: "Common", number: 69, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/069.png" },
{ name: "Clefairy Doll", type: "Trainer", rarity: "Rare", number: 70, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/070.png" },
{ name: "Computer Search", type: "Trainer", rarity: "Rare", number: 71, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/071.png" },
{ name: "Devolution Spray", type: "Trainer", rarity: "Rare", number: 72, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/072.png" },
{ name: "Imposter Professor Oak", type: "Trainer", rarity: "Rare", number: 73, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/073.png" },
{ name: "Item Finder", type: "Trainer", rarity: "Rare", number: 74, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/074.png" },
{ name: "Lass", type: "Trainer", rarity: "Rare", number: 75, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/075.png" },
{ name: "Pokemon Breeder", type: "Trainer", rarity: "Rare", number: 76, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/076.png" },
{ name: "Pokemon Trader", type: "Trainer", rarity: "Rare", number: 77, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/077.png" },
{ name: "Scoop Up", type: "Trainer", rarity: "Rare", number: 78, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/078.png" },
{ name: "Super Energy Removal", type: "Trainer", rarity: "Rare", number: 79, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/079.png" },
{ name: "Defender", type: "Trainer", rarity: "Uncommon", number: 80, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/080.png" },
{ name: "Energy Retrieval", type: "Trainer", rarity: "Uncommon", number: 81, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/081.png" },
{ name: "Full Healh", type: "Trainer", rarity: "Uncommon", number: 82, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/082.png" },
{ name: "Maintenance", type: "Trainer", rarity: "Uncommon", number: 83, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/083.png" },
{ name: "PlusPower", type: "Trainer", rarity: "Uncommon", number: 84, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/084.png" },
{ name: "Pokemon Center", type: "Trainer", rarity: "Uncommon", number: 85, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/085.png" },
{ name: "Pokemon Flute", type: "Trainer", rarity: "Uncommon", number: 86, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/086.png" },
{ name: "Pokedex", type: "Trainer", rarity: "Uncommon", number: 87, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/087.png" },
{ name: "Professor Oak", type: "Trainer", rarity: "Uncommon", number: 88, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/088.png" },
{ name: "Revive", type: "Trainer", rarity: "Uncommon", number: 89, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/089.png" },
{ name: "Super Potion", type: "Trainer", rarity: "Uncommon", number: 90, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/090.png" },
{ name: "Bill", type: "Trainer", rarity: "Common", number: 91, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/091.png" },
{ name: "Energy Removal", type: "Trainer", rarity: "Common", number: 92, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/092.png" },
{ name: "Gust of Wind", type: "Trainer", rarity: "Common", number: 93, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/093.png" },
{ name: "Potion", type: "Trainer", rarity: "Common", number: 94, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/094.png" },
{ name: "Switch", type: "Trainer", rarity: "Common", number: 95, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/095.png" },
{ name: "Double Normal Energy", type: "Energy", rarity: "Uncommon", number: 96, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/096.png" },
{ name: "Fighting Energy", type: "Energy", rarity: "Common", number: 97, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/097.png" },
{ name: "Fire Energy", type: "Energy", rarity: "Common", number: 98, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/098.png" },
{ name: "Grass Energy", type: "Energy", rarity: "Common", number: 99, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/099.png" },
{ name: "Lightning Energy", type: "Energy", rarity: "Common", number: 100, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/100.png" },
{ name: "Psychic Energy", type: "Energy", rarity: "Common", number: 101, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/101.png" },
{ name: "Water Energy", type: "Energy", rarity: "Common", number: 102, set: "Base", image_url: "https://www.digitaltq.com/images/tcg/baseset/102.png" },
{ name: "Clefable", type: "Normal", rarity: "Rare", number: 1, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//001.png" },
{ name: "Electrode", type: "Lightning", rarity: "Rare", number: 2, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//002.png" },
{ name: "Flareon", type: "Fire", rarity: "Rare", number: 3, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//003.png" },
{ name: "Jolteon", type: "Lightning", rarity: "Rare", number: 4, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//004.png" },
{ name: "Kangaskhan", type: "Normal", rarity: "Rare", number: 5, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//005.png" },
{ name: "Mr. Mime", type: "Psychic", rarity: "Rare", number: 6, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//006.png" },
{ name: "Nidoqueen", type: "Grass", rarity: "Rare", number: 7, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//007.png" },
{ name: "Pidgeot", type: "Normal", rarity: "Rare", number: 8, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//008.png" },
{ name: "Pinsir", type: "Grass", rarity: "Rare", number: 9, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//009.png" },
{ name: "Scyther", type: "Grass", rarity: "Rare", number: 10, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//010.png" },
{ name: "Snorlax", type: "Normal", rarity: "Rare", number: 11, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//011.png" },
{ name: "Vaporeon", type: "Water", rarity: "Rare", number: 12, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//012.png" },
{ name: "Venomoth", type: "Grass", rarity: "Rare", number: 13, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//013.png" },
{ name: "Victreebel", type: "Grass", rarity: "Rare", number: 14, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//014.png" },
{ name: "Vileplume", type: "Grass", rarity: "Rare", number: 15, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//015.png" },
{ name: "Wigglytuff", type: "Normal", rarity: "Rare", number: 16, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//016.png" },
{ name: "Clefable", type: "Normal", rarity: "Rare", number: 17, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//017.png" },
{ name: "Electrode", type: "Lightning", rarity: "Rare", number: 18, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//018.png" },
{ name: "Flareon", type: "Fire", rarity: "Rare", number: 19, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//019.png" },
{ name: "Jolteon", type: "Lightning", rarity: "Rare", number: 20, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//020.png" },
{ name: "Kangaskhan", type: "Normal", rarity: "Rare", number: 21, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//021.png" },
{ name: "Mr. Mime", type: "Psychic", rarity: "Rare", number: 22, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//022.png" },
{ name: "Nidoqueen", type: "Grass", rarity: "Rare", number: 23, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//023.png" },
{ name: "Pidgeot", type: "Normal", rarity: "Rare", number: 24, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//024.png" },
{ name: "Pinsir", type: "Grass", rarity: "Rare", number: 25, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//025.png" },
{ name: "Scyther", type: "Grass", rarity: "Rare", number: 26, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//026.png" },
{ name: "Snorlax", type: "Normal", rarity: "Rare", number: 27, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//027.png" },
{ name: "Vaporeon", type: "Water", rarity: "Rare", number: 28, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//028.png" },
{ name: "Venomoth", type: "Grass", rarity: "Rare", number: 29, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//029.png" },
{ name: "Victreebel", type: "Grass", rarity: "Rare", number: 30, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//030.png" },
{ name: "Vileplume", type: "Grass", rarity: "Rare", number: 31, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//031.png" },
{ name: "Wigglytuff", type: "Normal", rarity: "Rare", number: 32, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//032.png" },
{ name: "Butterfree", type: "Grass", rarity: "Uncommon", number: 33, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//033.png" },
{ name: "Dodrio", type: "Normal", rarity: "Uncommon", number: 34, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//034.png" },
{ name: "Exeggutor", type: "Grass", rarity: "Uncommon", number: 35, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//035.png" },
{ name: "Fearow", type: "Normal", rarity: "Uncommon", number: 36, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//036.png" },
{ name: "Gloom", type: "Grass", rarity: "Uncommon", number: 37, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//037.png" },
{ name: "Lickitung", type: "Normal", rarity: "Uncommon", number: 38, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//038.png" },
{ name: "Marowak", type: "Fighting", rarity: "Uncommon", number: 39, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//039.png" },
{ name: "Nidorina", type: "Grass", rarity: "Uncommon", number: 40, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//040.png" },
{ name: "Parasect", type: "Grass", rarity: "Uncommon", number: 41, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//041.png" },
{ name: "Persian", type: "Normal", rarity: "Uncommon", number: 42, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//042.png" },
{ name: "Primeape", type: "Fighting", rarity: "Uncommon", number: 43, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//043.png" },
{ name: "Rapidash", type: "Fire", rarity: "Uncommon", number: 44, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//044.png" },
{ name: "Rhydon", type: "Fighting", rarity: "Uncommon", number: 45, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//045.png" },
{ name: "Seaking", type: "Water", rarity: "Uncommon", number: 46, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//046.png" },
{ name: "Tauros", type: "Normal", rarity: "Uncommon", number: 47, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//047.png" },
{ name: "Weepinbell", type: "Grass", rarity: "Uncommon", number: 48, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//048.png" },
{ name: "Bellsprout", type: "Grass", rarity: "Common", number: 49, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//049.png" },
{ name: "Cubone", type: "Fighting", rarity: "Common", number: 50, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//050.png" },
{ name: "Eevee", type: "Normal", rarity: "Common", number: 51, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//051.png" },
{ name: "Exeggcute", type: "Grass", rarity: "Common", number: 52, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//052.png" },
{ name: "Goldeen", type: "Water", rarity: "Common", number: 53, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//053.png" },
{ name: "Jigglypuff", type: "Normal", rarity: "Common", number: 54, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//054.png" },
{ name: "Mankey", type: "Fighting", rarity: "Common", number: 55, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//055.png" },
{ name: "Meowth", type: "Normal", rarity: "Common", number: 56, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//056.png" },
{ name: "Nidoran♀", type: "Grass", rarity: "Common", number: 57, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//057.png" },
{ name: "Oddish", type: "Grass", rarity: "Common", number: 58, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//058.png" },
{ name: "Paras", type: "Grass", rarity: "Common", number: 59, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//059.png" },
{ name: "Pikachu", type: "Lightning", rarity: "Common", number: 60, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//060.png" },
{ name: "Rhyhorn", type: "Fighting", rarity: "Common", number: 61, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//061.png" },
{ name: "Spearow", type: "Normal", rarity: "Common", number: 62, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//062.png" },
{ name: "Venonat", type: "Grass", rarity: "Common", number: 63, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//063.png" },
{ name: "Poké Ball", type: "Trainer", rarity: "Common", number: 64, set: "Jungle", image_url: "https://www.digitaltq.com/images/tcg/jungleset//064.png" },
{ name: "Aerodactyl", type: "Fighting", rarity: "Rare Holo", number: 1, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/001.png" },
{ name: "Articuno", type: "Water", rarity: "Rare Holo", number: 2, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/002.png" },
{ name: "Ditto", type: "Normal", rarity: "Rare Holo", number: 3, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/003.png" },
{ name: "Dragonite", type: "Normal", rarity: "Rare Holo", number: 4, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/004.png" },
{ name: "Gengar", type: "Psychic", rarity: "Rare Holo", number: 5, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/005.png" },
{ name: "Haunter", type: "Psychic", rarity: "Rare Holo", number: 6, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/006.png" },
{ name: "Hitmonlee", type: "Fighting", rarity: "Rare Holo", number: 7, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/007.png" },
{ name: "Hypno", type: "Psychic", rarity: "Rare Holo", number: 8, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/008.png" },
{ name: "Kabutops", type: "Fighting", rarity: "Rare Holo", number: 9, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/009.png" },
{ name: "Lapras", type: "Water", rarity: "Rare Holo", number: 10, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/010.png" },
{ name: "Magneton", type: "Lightning", rarity: "Rare Holo", number: 11, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/011.png" },
{ name: "Moltres", type: "Fire", rarity: "Rare Holo", number: 12, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/012.png" },
{ name: "Muk", type: "Grass", rarity: "Rare Holo", number: 13, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/013.png" },
{ name: "Raichu", type: "Lightning", rarity: "Rare Holo", number: 14, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/014.png" },
{ name: "Zapdos", type: "Lightning", rarity: "Rare Holo", number: 15, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/015.png" },
{ name: "Aerodactyl", type: "Fighting", rarity: "Rare", number: 16, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/016.png" },
{ name: "Articuno", type: "Water", rarity: "Rare", number: 17, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/017.png" },
{ name: "Ditto", type: "Normal", rarity: "Rare", number: 18, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/018.png" },
{ name: "Dragonite", type: "Normal", rarity: "Rare", number: 19, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/019.png" },
{ name: "Gengar", type: "Psychic", rarity: "Rare", number: 20, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/020.png" },
{ name: "Haunter", type: "Psychic", rarity: "Rare", number: 21, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/021.png" },
{ name: "Hitmonlee", type: "Fighting", rarity: "Rare", number: 22, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/022.png" },
{ name: "Hypno", type: "Psychic", rarity: "Rare", number: 23, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/023.png" },
{ name: "Kabutops", type: "Fighting", rarity: "Rare", number: 24, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/024.png" },
{ name: "Lapras", type: "Water", rarity: "Rare", number: 25, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/025.png" },
{ name: "Magneton", type: "Lightning", rarity: "Rare", number: 26, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/026.png" },
{ name: "Moltres", type: "Fire", rarity: "Rare", number: 27, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/027.png" },
{ name: "Muk", type: "Grass", rarity: "Rare", number: 28, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/028.png" },
{ name: "Raichu", type: "Lightning", rarity: "Rare", number: 29, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/029.png" },
{ name: "Zapdos", type: "Lightning", rarity: "Rare", number: 30, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/030.png" },
{ name: "Arbok", type: "Grass", rarity: "Uncommon", number: 31, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/031.png" },
{ name: "Cloyster", type: "Water", rarity: "Uncommon", number: 32, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/032.png" },
{ name: "Gastly", type: "Psychic", rarity: "Uncommon", number: 33, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/033.png" },
{ name: "Golbat", type: "Grass", rarity: "Uncommon", number: 34, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/034.png" },
{ name: "Golduck", type: "Water", rarity: "Uncommon", number: 35, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/035.png" },
{ name: "Golem", type: "Fighting", rarity: "Uncommon", number: 36, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/036.png" },
{ name: "Graveler", type: "Fighting", rarity: "Uncommon", number: 37, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/037.png" },
{ name: "Kingler", type: "Water", rarity: "Uncommon", number: 38, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/038.png" },
{ name: "Magmar", type: "Fire", rarity: "Uncommon", number: 39, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/039.png" },
{ name: "Omastar", type: "Water", rarity: "Uncommon", number: 40, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/040.png" },
{ name: "Sandslash", type: "Fighting", rarity: "Uncommon", number: 41, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/041.png" },
{ name: "Seadra", type: "Water", rarity: "Uncommon", number: 42, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/042.png" },
{ name: "Slowbro", type: "Psychic", rarity: "Uncommon", number: 43, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/043.png" },
{ name: "Tentacruel", type: "Water", rarity: "Uncommon", number: 44, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/044.png" },
{ name: "Weezing", type: "Grass", rarity: "Uncommon", number: 45, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/045.png" },
{ name: "Ekans", type: "Grass", rarity: "Common", number: 46, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/046.png" },
{ name: "Geodude", type: "Fighting", rarity: "Common", number: 47, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/047.png" },
{ name: "Grimer", type: "Grass", rarity: "Common", number: 48, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/048.png" },
{ name: "Horsea", type: "Water", rarity: "Common", number: 49, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/049.png" },
{ name: "Kabuto", type: "Fighting", rarity: "Common", number: 50, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/050.png" },
{ name: "Krabby", type: "Water", rarity: "Common", number: 51, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/051.png" },
{ name: "Omanyte", type: "Water", rarity: "Common", number: 52, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/052.png" },
{ name: "Psyduck", type: "Water", rarity: "Common", number: 53, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/053.png" },
{ name: "Shellder", type: "Water", rarity: "Common", number: 54, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/054.png" },
{ name: "Slowpoke", type: "Psychic", rarity: "Common", number: 55, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/055.png" },
{ name: "Tentacool", type: "Water", rarity: "Common", number: 56, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/056.png" },
{ name: "Zubat", type: "Grass", rarity: "Common", number: 57, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/057.png" },
{ name: "Mr. Fuji", type: "Trainer", rarity: "Uncommon", number: 58, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/058.png" },
{ name: "Energy Search", type: "Trainer", rarity: "Common", number: 59, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/059.png" },
{ name: "Gambler", type: "Trainer", rarity: "Common", number: 60, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/060.png" },
{ name: "Recycle", type: "Trainer", rarity: "Common", number: 61, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/061.png" },
{ name: "Mysterious Fossil", type: "Trainer", rarity: "Common", number: 62, set: "Fossil", image_url: "https://www.digitaltq.com/images/tcg/fossilset/062.png" },
{ name: "Dark Alakazam", type: "Psychic", rarity: "Rare Holo", number: 1, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/001.png" },
{ name: "Dark Arbok", type: "Grass", rarity: "Rare Holo", number: 2, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/002.png" },
{ name: "Dark Blastoise", type: "Water", rarity: "Rare Holo", number: 3, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/003.png" },
{ name: "Dark Charizard", type: "Fire", rarity: "Rare Holo", number: 4, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/004.png" },
{ name: "Dark Dragonite", type: "Normal", rarity: "Rare Holo", number: 5, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/005.png" },
{ name: "Dark Dugtrio", type: "Fighting", rarity: "Rare Holo", number: 6, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/006.png" },
{ name: "Dark Golbat", type: "Grass", rarity: "Rare Holo", number: 7, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/007.png" },
{ name: "Dark Gyarados", type: "Water", rarity: "Rare Holo", number: 8, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/008.png" },
{ name: "Dark Hypno", type: "Psychic", rarity: "Rare Holo", number: 9, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/009.png" },
{ name: "Dark Machamp", type: "Fighting", rarity: "Rare Holo", number: 10, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/010.png" },
{ name: "Dark Magneton", type: "Lightning", rarity: "Rare Holo", number: 11, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/011.png" },
{ name: "Dark Slowbro", type: "Psychic", rarity: "Rare Holo", number: 12, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/012.png" },
{ name: "Dark Vileplume", type: "Grass", rarity: "Rare Holo", number: 13, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/013.png" },
{ name: "Dark Weezing", type: "Grass", rarity: "Rare Holo", number: 14, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/014.png" },
{ name: "Here Comes Team Rocket!", type: "Trainer", rarity: "Rare Holo", number: 15, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/015.png" },
{ name: "Rocket's Sneak Attack", type: "Trainer", rarity: "Rare Holo", number: 16, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/016.png" },
{ name: "Rainbow Energy", type: "Energy", rarity: "Rare Holo", number: 17, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/017.png" },
{ name: "Dark Alakazam", type: "Psychic", rarity: "Rare", number: 18, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/018.png" },
{ name: "Dark Arbok", type: "Grass", rarity: "Rare", number: 19, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/019.png" },
{ name: "Dark Blastoise", type: "Water", rarity: "Rare", number: 20, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/020.png" },
{ name: "Dark Charizard", type: "Fire", rarity: "Rare", number: 21, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/021.png" },
{ name: "Dark Dragonite", type: "Normal", rarity: "Rare", number: 22, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/022.png" },
{ name: "Dark Dugtrio", type: "Fighting", rarity: "Rare", number: 23, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/023.png" },
{ name: "Dark Golbat", type: "Grass", rarity: "Rare", number: 24, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/024.png" },
{ name: "Dark Gyarados", type: "Water", rarity: "Rare", number: 25, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/025.png" },
{ name: "Dark Hypno", type: "Psychic", rarity: "Rare", number: 26, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/026.png" },
{ name: "Dark Machamp", type: "Fighting", rarity: "Rare", number: 27, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/027.png" },
{ name: "Dark Magneton", type: "Lightning", rarity: "Rare", number: 28, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/028.png" },
{ name: "Dark Slowbro", type: "Psychic", rarity: "Rare", number: 29, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/029.png" },
{ name: "Dark Vileplume", type: "Grass", rarity: "Rare", number: 30, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/030.png" },
{ name: "Dark Weezing", type: "Grass", rarity: "Rare", number: 31, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/031.png" },
{ name: "Dark Charmeleon", type: "Fire", rarity: "Uncommon", number: 32, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/032.png" },
{ name: "Dark Dragonair", type: "Normal", rarity: "Uncommon", number: 33, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/033.png" },
{ name: "Dark Electrode", type: "Lightning", rarity: "Uncommon", number: 34, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/034.png" },
{ name: "Dark Flareon", type: "Fire", rarity: "Uncommon", number: 35, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/035.png" },
{ name: "Dark Gloom", type: "Grass", rarity: "Uncommon", number: 36, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/036.png" },
{ name: "Dark Golduck", type: "Water", rarity: "Uncommon", number: 37, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/037.png" },
{ name: "Dark Jolteon", type: "Lightning", rarity: "Uncommon", number: 38, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/038.png" },
{ name: "Dark Kadabra", type: "Psychic", rarity: "Uncommon", number: 39, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/039.png" },
{ name: "Dark Machoke", type: "Fighting", rarity: "Uncommon", number: 40, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/040.png" },
{ name: "Dark Muk", type: "Grass", rarity: "Uncommon", number: 41, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/041.png" },
{ name: "Dark Persian", type: "Normal", rarity: "Uncommon", number: 42, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/042.png" },
{ name: "Dark Primeape", type: "Fighting", rarity: "Uncommon", number: 43, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/043.png" },
{ name: "Dark Rapidash", type: "Fire", rarity: "Uncommon", number: 44, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/044.png" },
{ name: "Dark Vaporeon", type: "Water", rarity: "Uncommon", number: 45, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/045.png" },
{ name: "Dark Wartortle", type: "Water", rarity: "Uncommon", number: 46, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/046.png" },
{ name: "Magikarp", type: "Water", rarity: "Uncommon", number: 47, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/047.png" },
{ name: "Porygon", type: "Normal", rarity: "Uncommon", number: 48, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/048.png" },
{ name: "Abra", type: "Psychic", rarity: "Common", number: 49, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/049.png" },
{ name: "Charmander", type: "Fire", rarity: "Common", number: 50, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/050.png" },
{ name: "Dark Raticate", type: "Normal", rarity: "Common", number: 51, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/051.png" },
{ name: "Diglett", type: "Fighting", rarity: "Common", number: 52, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/052.png" },
{ name: "Dratini", type: "Normal", rarity: "Common", number: 53, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/053.png" },
{ name: "Drowzee", type: "Psychic", rarity: "Common", number: 54, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/054.png" },
{ name: "Eevee", type: "Normal", rarity: "Common", number: 55, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/055.png" },
{ name: "Ekans", type: "Grass", rarity: "Common", number: 56, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/056.png" },
{ name: "Grimer", type: "Grass", rarity: "Common", number: 57, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/057.png" },
{ name: "Koffing", type: "Grass", rarity: "Common", number: 58, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/058.png" },
{ name: "Machop", type: "Fighting", rarity: "Common", number: 59, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/059.png" },
{ name: "Magnemite", type: "Lightning", rarity: "Common", number: 60, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/060.png" },
{ name: "Mankey", type: "Fighting", rarity: "Common", number: 61, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/061.png" },
{ name: "Meowth", type: "Normal", rarity: "Common", number: 62, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/062.png" },
{ name: "Oddish", type: "Grass", rarity: "Common", number: 63, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/063.png" },
{ name: "Ponyta", type: "Fire", rarity: "Common", number: 64, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/064.png" },
{ name: "Psyduck", type: "Water", rarity: "Common", number: 65, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/065.png" },
{ name: "Rattata", type: "Normal", rarity: "Common", number: 66, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/066.png" },
{ name: "Slowpoke", type: "Psychic", rarity: "Common", number: 67, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/067.png" },
{ name: "Squirtle", type: "Water", rarity: "Common", number: 68, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/068.png" },
{ name: "Voltorb", type: "Lightning", rarity: "Common", number: 69, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/069.png" },
{ name: "Zubat", type: "Grass", rarity: "Common", number: 70, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/070.png" },
{ name: "Here Comes Team Rocket!", type: "Trainer", rarity: "Rare", number: 71, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/071.png" },
{ name: "Rocket's Sneak Attack", type: "Trainer", rarity: "Rare", number: 72, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/072.png" },
{ name: "The Boss's Way", type: "Trainer", rarity: "Uncommon", number: 73, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/073.png" },
{ name: "Challenge!", type: "Trainer", rarity: "Uncommon", number: 74, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/074.png" },
{ name: "Digger", type: "Trainer", rarity: "Uncommon", number: 75, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/075.png" },
{ name: "Imposter Oak's Revenge", type: "Trainer", rarity: "Uncommon", number: 76, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/076.png" },
{ name: "Nightly Garbage Run", type: "Trainer", rarity: "Uncommon", number: 77, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/077.png" },
{ name: "Goop Gas Attack", type: "Trainer", rarity: "Common", number: 78, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/078.png" },
{ name: "Sleep!", type: "Trainer", rarity: "Common", number: 79, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/079.png" },
{ name: "Rainbow Energy", type: "Energy", rarity: "Rare", number: 80, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/080.png" },
{ name: "Full Heal Energy", type: "Normal", rarity: "Uncommon", number: 81, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/081.png" },
{ name: "Potion Energy", type: "Normal", rarity: "Uncommon", number: 82, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/082.png" },
{ name: "Dark Raichu", type: "Lightning", rarity: "Rare Holo", number: 83, set: "Team Rocket", image_url: "https://www.digitaltq.com/images/tcg/teamrocket/083.png" }
].each do |card_attrs|
  Card.find_or_create_by!(name: card_attrs[:name], serie_set_id: serie_sets[card_attrs[:set]]) do |card|
    card.card_type_id = card_types[card_attrs[:type]]
    card.card_rarity_id = card_rarities[card_attrs[:rarity]]
    card.image_url = card_attrs[:image_url]
    card.number = card_attrs[:number]
    card.image_url = card_attrs[:image_url]
  end
end

